# Generated by Django 3.2.6 on 2021-08-12 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name of Acceptor')),
                ('address', models.CharField(max_length=200, verbose_name='Address')),
                ('phoneno', models.CharField(max_length=10, verbose_name='Phone Number')),
                ('age', models.IntegerField(max_length=2, verbose_name='Age')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('T', 'Trans')], max_length=1, verbose_name='Gender')),
                ('bloodgroup', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('O+', 'O+'), ('O-', 'O-'), ('B+', 'B+'), ('B-', 'B-'), ('AB-', 'AB-'), ('AB+', 'AB+')], max_length=3, verbose_name='Blood Group')),
                ('dayofaccept', models.DateTimeField(verbose_name='Day of Accepting')),
            ],
        ),
        migrations.CreateModel(
            name='Admin1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Donate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name of Donar')),
                ('address', models.CharField(max_length=200, verbose_name='Address')),
                ('phoneno', models.CharField(max_length=10, verbose_name='Phone Number')),
                ('age', models.IntegerField(max_length=2, verbose_name='Age')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('T', 'Trans')], max_length=1, verbose_name='Gender')),
                ('bloodgroup', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('O+', 'O+'), ('O-', 'O-'), ('B+', 'B+'), ('B-', 'B-'), ('AB-', 'AB-'), ('AB+', 'AB+')], max_length=3, verbose_name='Blood Group')),
                ('dayofdonate', models.DateTimeField(verbose_name='Day of Donating')),
            ],
        ),
    ]
