# Generated by Django 3.2.6 on 2021-08-12 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plasmaapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accept',
            name='age',
            field=models.IntegerField(verbose_name='Age'),
        ),
    ]
