# Generated by Django 3.2.6 on 2021-08-12 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plasmaapp', '0003_alter_donate_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accept',
            name='dayofaccept',
            field=models.DateField(verbose_name='Day of Accepting'),
        ),
        migrations.AlterField(
            model_name='donate',
            name='dayofdonate',
            field=models.DateField(verbose_name='Day of Donating'),
        ),
    ]
