# Generated by Django 3.2.6 on 2021-08-12 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plasmaapp', '0007_auto_20210812_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accept',
            name='dayofaccept',
            field=models.DateField(null=True, verbose_name='Day of Accepting'),
        ),
        migrations.AlterField(
            model_name='accept',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='donate',
            name='dayofdonate',
            field=models.DateField(null=True, verbose_name='Day of Donating'),
        ),
    ]
