# Generated by Django 3.2.6 on 2021-08-12 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plasmaapp', '0009_auto_20210812_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accept',
            name='status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('GotIt', 'GotIt'), ('Rejected', 'Rejected')], default='Pending', max_length=20, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='donate',
            name='status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Donated', 'Donated'), ('Rejected', 'Rejected')], default='Pending', max_length=20, null=True, verbose_name='Status'),
        ),
    ]
