# Generated by Django 3.2.6 on 2021-08-13 17:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plasmaapp', '0010_auto_20210812_2123'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='Address')),
                ('phoneno', models.CharField(blank=True, max_length=10, null=True, verbose_name='Phone Number')),
                ('age', models.IntegerField(verbose_name='Age')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('T', 'Trans')], max_length=1, null=True, verbose_name='Gender')),
                ('bloodgroup', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('O+', 'O+'), ('O-', 'O-'), ('B+', 'B+'), ('B-', 'B-'), ('AB-', 'AB-'), ('AB+', 'AB+')], max_length=3, verbose_name='Blood Group')),
                ('dayofaccept', models.DateField(blank=True, null=True, verbose_name='Day of Accepting')),
                ('need', models.CharField(blank=True, choices=[('Acceptor', 'Acceptor'), ('Donator', 'Donator')], max_length=20, null=True, verbose_name='Need')),
                ('status', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('GotIt', 'GotIt'), ('Rejected', 'Rejected')], default='Pending', max_length=20, null=True, verbose_name='Status')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
