# Generated by Django 3.2.6 on 2021-08-15 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plasmaapp', '0015_alter_customer_need'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, default='abc@gmail.com', max_length=254, null=True, verbose_name='Email'),
        ),
    ]
