# Generated by Django 3.2.6 on 2021-08-16 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plasmaapp', '0017_customer_prescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='prescription',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
